### ISSUE TITLE
consider a different workflow trigger

### ISSUE THREAD

**Issue by cullerth** [cullerth/marc-actions#1]
As written, the workflow trigger is any push to the main branch. It would be nice to have the workflow trigger instead be when a new data file is added to the inputs subdirectory.

**Comment by chrisdaaz** [comment]
You can use `paths` as a filter in your workflow file ([see here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs)):

```yml
on:
  push:
    branches:
      - 'main'
    paths:
      - 'inputs/*.xml'
```
